### ISSUE TITLE
Squaring Algorithm

### ISSUE THREAD

**Issue by michkowalczuk** [jgaffuri/OpenCarto#2]
Dear Mr Gaffuri,
I'm GIS and programming enthusiast, Now I'm doing research about regularize building outlines from noisy polygons. I found your project and Squaring method but It is not clear for me because of lack of comments in your code. Could you give me a little explanation about algorithm that you have used? Maybe reference to some article that you based on?
I will be very grateful!

Sincerely
Michał

**Comment by jgaffuri** [comment]
Dear Michał,
Sorry for the late reply. The algorithm is at least partially described in this paper:
Gaffuri, J., Nov. 2009. Three reuse example of a generic deformation model in map generalisation. In: 24th International Cartographic Conference.

It is available online:
http://icaci.org/files/documents/ICC_proceedings/ICC2009/html/refer/19.html
http://www.ahahah.eu/data/doc/2009_icc_gaffuri.pdf

Bye !
julien
